### ISSUE TITLE
Wie gebe ich denn da 10 ein ??

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [mwageringel/everest#1]
![Screenshot_20220810-075944-01](https://user-images.githubusercontent.com/61406324/183826654-6afd0298-ee96-49ed-8395-6a3489d5fed7.jpeg)

**Comment by mwageringel** [comment]
Hallo @mondlicht-und-sterne, probier mal alle Eingabemöglichkeiten durch. ;)
