### ISSUE TITLE
severe graphics glitches on LineageOS

### ISSUE THREAD

**Issue by sans-c** [mwageringel/everest#17]
### Issue:
After starting the app, everything looks fine. Any scrolling quickly messes everything up completely. I attached some screenshots but the glitches aren't purely static. During any animation there is also some severe flickering. The app is practically unusable for me (which seems to be a pity ;)).

### Platform used:
Old phone, 2GB RAM, Adreno 320 GPU, running the latest Lineage 18.1 build (Android 11)

If you need any more info, let me know. Thanks in advance.

### Screenshots:

![image](https://user-images.githubusercontent.com/52868970/188732368-241cc4a5-b9b0-438b-8d26-b09cc2b5b27d.png)

------

![image](https://user-images.githubusercontent.com/52868970/188732403-4abc138e-ee13-470a-a5a4-8bc75a702428.png)

------
![image](https://user-images.githubusercontent.com/52868970/188732426-70d71626-944c-4acf-a5f4-6b61c3af7abf.png)

**Comment by mwageringel** [comment]
Thanks for reporting this. It looks like this is an issue between Flutter and LineageOS as described at https://github.com/flutter/flutter/issues/105093. To confirm this, you could try a different Flutter app such as Finamp.

I'm afraid there's nothing I can do to solve this right now. As a workaround, you could try the [browser version](https://mwageringel.github.io/everest/).

**Comment by sans-c** [comment]
>To confirm this, you could try a different Flutter app such as Finamp.

Yup, this is it. Same issues there.

>As a workaround, you could try the [browser version](https://mwageringel.github.io/everest/).

Already playing. :) Thank you for your effort.

**Comment by mwageringel** [comment]
The upstream Flutter issue has been solved. The fix is included in our version 1.1.6 that's now on f-droid, but I haven't tested it. Please re-open if this is still an issue.

**Comment by sans-c** [comment]
> The upstream Flutter issue has been solved. The fix is included in our version 1.1.6 that's now on f-droid, but I haven't tested it. Please re-open if this is still an issue.

Seems fixed indeed. Thanks for notifying. :)
