### ISSUE TITLE
Stuck in level 2 with X + X

### ISSUE THREAD

**Issue by bovergaauw** [mwageringel/everest#3]
I understand that the objective of the game is to discover the rules of it, but no answer to the sum X + X will validate. Two "digit" responses appear to be interpret as to successive one-"digit" responses, and none seems accepted, meaning I'm stuck. Is this an error or a feature?

**Comment by mwageringel** [comment]
Hi @bovergaauw, thanks a lot for your feedback. All the answers are indeed single digits. X + X is 9, but it will only validate if all three questions in that group are answered correctly.

By clicking on the arrow of Level 2, you will navigate to a second page of individual single-response questions (as in the first level) which can help with finding the correct answers to complete Level 2. I am thinking of ways to make navigating to this second page more intuitive.

**Comment by Hypoon** [comment]
> it will only validate if all three questions in that group are answered correctly.

When I was playing, it wasn't clear to me either how the indicator worked for sets of expressions. I figured it out, but I don't think that's supposed to be part of the puzzle, haha!

Regarding the extra pages of questions, it might be useful to move the advancement questions onto separate pages as well. You could have one row per level, with a button for "training" and a button for "advance", which implies that the training is optional. (Of course, you can use whatever labels you like to describe them. "Practice" and "Exam" would sound very pedagogical.)

**Comment by mwageringel** [comment]
> Regarding the extra pages of questions, it might be useful to move the advancement questions onto separate pages as well. You could have one row per level, with a button for "training" and a button for "advance", which implies that the training is optional. (Of course, you can use whatever labels you like to describe them. "Practice" and "Exam" would sound very pedagogical.)

It really seems to be quite difficult to make this intuitive. This particular part of the app has already gone through several iterations and tests.

The way it is implemented in version 1.1.3 is that the advancement questions for levels 1-3 only get shown after visiting the subpages, so you are forced to click on the arrow. For the later levels, they still show right away, so they can advertise the goal of the level. At that point, the interaction between the main and sub pages might be clearer, but I've also added an info icon that shows up if the subpage has not been visited.

I'd like to avoid introducing descriptive text, as it is not as universally understandable.

**Comment by Hypoon** [comment]
> I'd like to avoid introducing descriptive text, as it is not as universally understandable.

On paper, I like that objective. The more text you use, the more text you might have to translate into other languages. Also, the lack of text can make the puzzles more mysterious and enhance the feeling of reward when you figure it out.

The problem is that sometimes making something visually intuitive is very, very difficult. I downloaded a Sudoku app a few days ago, where instead of solving the puzzle directly, you're actually intended to program in constraints to help the puzzle solve itself. It sounds really cool! ...But I can't figure out how to actually play it.

App design is hard, and you certainly know more about it than I do. Please feel free to disregard anything I suggest!

**Comment by mwageringel** [comment]
Version 1.1.3 is now available on F-Droid which includes the new behavior, so I am marking this issue as resolved. Feel free to reopen it if you still get stuck.
