### ISSUE TITLE
Everest Solutions - Spoilers

### ISSUE THREAD

**Issue by WindUpCitrus** [mwageringel/everest#33]
Everest PC (2022) 
A Math Puzzle Game Designed by mwageringel
Guide by Wind-UpCitrus
Table of Contents
1 - Intro
2 - Puzzles
Level 1
Level 1 Test
Level 2
Level 2 Test
Level 3 
Level 3 Test
Level 4
Level 4 Test
Level 5
Level 5 Test
Level 6 
Level 6 Test
Level 7 
Level 7 Test
Level 8
Level 8 Test
Level 9
Level 9 Test
Level 10 
Level 10 Test
Level 11
Level 11 Test
Level 12 
Level 12 Test
Level 13
Level 13 Test
Level 14
Level 14 Test
Level 15
Level 15 Test
Level 16
Level 16 Test

1.0 

1 - Intro

Link: https://mwageringel.github.io/everest/demo/

This guide is meant to help solve the puzzle game. All answers included including what I found to help solve this. Thanks to friends on discord for helping me understand. 

<summary>Spoiler
<details>

Note: This Puzzle uses a Base 11 system and have 16 levels. 

EX: Set [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, X]

All math problems are derived from this. 

As it uses basic arithmetic and uses the last digit for solution, only the last digit matters. 
https://math.tools/table/multiplication/base/11

Or use any website with a base 11 multiplier. 

The puzzles have a test where you have to solve at least 3 puzzles 

[…]

Credit to Essays on the Foundations of Mathematics by Moritz Pasch.

2 - Puzzles

First Puzzle: 

1 + 2 = 3

An easy start to the puzzle one can use basic base 10 math for it. 

2.1 - Level 1: 

[…]

This is the start of the use of base 11, in this case 0 still represents 0 in base 10 and X is the largest value, the equivalent of 10 in base 11. 

[…]

Level 1 Test
[…]
Obvious as X is our equivalent to 10
[…]
The rule is to roll over to the new set, what comes after X we go all the way back to the beginning of the set,number zero. 

Level 2 
[…]
Explanation 5 and 5 goes to X remainder 2, then 0, then 1 in the set. or Can be thought of as 12-1 = 11, last digit 1, answer is 1

[…]

Level 2 Test
[…]

Level 3
Now with Subtractions
[…]

Level 4 
Now we have multiplication.
[…]

Level 5 
[…]

Level 6
[…]

Level 7 
Now we are introduced to sets. the sets have a 4 dots in a column as an arbitrary symbol, this does not appear in any textbook or google result. 
[…]

Level 8 
Now we have multiplication

[…]

Level 9 
[…]

Level 10 
[…]

Level 11 
[…]

Level 12
[…]

Level 13
[…]

Level 14
[…]

Level 15
Now we introduce a ? to the values
[…]

Level 16
This time we are introduced to our last challenge, perfect squares.
[…]

Congratulations, you made it. 

Thank you for the dev for making this game and giving me the runaround. I hope others get a chance to learn or progress if they never got a chance to get a solution, since I didn't see any guides online for stuff like Base 11 Arithmetic. 

</details>
</summary>

*Edit: Solutions removed by maintainer.*

**Comment by mwageringel** [comment]
Thanks for your comment. As others have pointed out, some form of in-game tips or help feature might be useful to help players progress. Having all the solutions takes away key aspects of the game though, so I have removed them from your post. The source code in this repository intentionally does not contain the solutions and I'd like to keep it that way.
