### ISSUE TITLE
Allow Translations

### ISSUE THREAD

**Issue by vrifox** [mwageringel/everest#4]
I would like to translate the game to german. 

If you're interested and don't know how it's done, here's the [documentation](https://docs.flutter.dev/development/accessibility-and-localization/internationalization). :)
I am interested in implementing it myself, but I can't guarantee anything, since my experience with flutter and dart is very limited.

Thanks for this nice game, it's awesome! :tada:

**Comment by mwageringel** [comment]
Hi Vri, thanks for your interest and the kind words. :) I'd very much welcome your contribution.

So far, I have not looked much into internationalization with Flutter yet, but do not hesitate to let me know if there is anything I can do to assist. To get started, currently all the Flutter widgets are contained in the file `lib/main.dart`. Also, the first lines of the Makefile are what I use to build the app, which might be of some use.

**Comment by vrifox** [comment]
Thank you for your fast response and the hints you've given me, I will definitely look into it later. As soon as I make progress I will reply to this Issue. :)
