### ISSUE TITLE
Missing Font

### ISSUE THREAD

**Issue by vrifox** [mwageringel/everest#5]
The font `fonts/NotoSansMath-Regular.ttf` as declared in pubspec.yaml is missing in this repository and has to be manually added to complete the build process. Is that intentional?

## Error Log:
```
$ flutter build web

💪 Building with sound null safety 💪

Error: unable to locate asset entry in pubspec.yaml: "fonts/NotoSansMath-Regular.ttf".
Target web_release_bundle failed: Exception: Failed to bundle asset files.
Compiling lib/main.dart for the Web...                             414ms
Exception: Failed to compile application for the Web.
```

**Comment by vrifox** [comment]
Nevermind, I used `flutter build  web` instead of `make` 🤦‍♀️😅

**Comment by mwageringel** [comment]
For development purposes, also `flutter run` is very useful, as it allows hot reloading, so it is much faster than rebuilding everything with `flutter build web`. It requires a Chromium-based browser though, or a connected device.
