### ISSUE TITLE
Make the link to the website clickable in "About"

### ISSUE THREAD

**Issue by Porkepix** [mwageringel/everest#7]
As asked with the title, the link the "about" popup currently isn't clickable, it should be.

Fun fact added to it, as the link wasn't clickable and I was too lazy at first, this repo seems to be unknown to Google (not DDG), "mwageringel github everest" find nothing relevant to here nor the website, but removing "everest" from the query does find your profile or other repos.

**Comment by mwageringel** [comment]
Thanks for the report. This should be fixed in the next release.

Interesting find about the search engine behavior. I have no idea what might be the cause for that. The repository is only a few weeks old, so it might just be a matter of time for Google to catch up.
