### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by Paeoniaofficinalis** [mwageringel/everest#8]
It's fun, gladly more of it!

**Comment by mwageringel** [comment]
Thank you for the kind words. :) Much appreciated. I'm open to new ideas for possible extensions, but can't make any promises. I think it might be best to explore completely different areas, rather than repeating the same concept at a higher difficulty.

**Comment by HROMANO** [comment]
Thanks for the game. Maybe too short, I only began to use pencil and paper at level 15. Probably harder with 13 or 17 instead of 11?
